services:
  postgres-app:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - PGDATA=/data/postgres
    volumes:
      - superchain-testnet-tools-indexer-postgres-data:/data/postgres

volumes:
  superchain-testnet-tools-indexer-postgres-data: